export enum Fields {
	Checkbox = 'checkbox',
	ColorPicker = 'colorpicker',
	Time = 'time',
	TimeUtc = 'timeutc',
	Date = 'date',
	DateTime = 'datetime',
	DateTimeUtc = 'datetimeutc',
	Json = 'json',
	Text = 'text',
	TextArea = 'textarea',
	Toggle = 'toggle',
	Xml = 'xml',
	Html = 'html',
	ProgressBar = 'progressbar',
	Icon = 'icon',
	Numeric = 'numeric',
	File = 'file',
	Select = 'select',
	Image = 'image',
	Flag = 'flag',
	Button = 'button',
	Message = 'message',
	Password = 'password',
	UUID = 'uuid',
	Bql = 'bql',
}

export default Fields;
