const defaultFieldProperty = {
	name: undefined,
	label: undefined,
	design: false,
	readOnly: false,
	disabled: false,
	required: false,
	searchable: false,
	loading: false,
	multiple: false,
	error: false,
	focus: false,
	value: undefined,
	displayValue: undefined,
	content: undefined,
	header: undefined,
	length: undefined,
	precision: undefined,
	scale: undefined,
	fileName: undefined,
	dataType: undefined,
	translate: false,
	primary: false,
	secondary: false,
	success: false,
	warning: false,
	size: undefined,
	color: undefined,
};

export default defaultFieldProperty;
